---
title: "Week 1 Slides"
format: revealjs
---

# Welcome to Fundamentals of Data Science in `R` (FDS)

## About the Course

This is a double-badged module: MATH2051 and MATH6195. Taught material:

- 1 hour lecture (16:00-17:00 in 58/1007, L/R C)
- 2 hour lab (Mondays, 14:00-16:00 in 25/1009)

## Lectures

- 1 hour session.
- I will demo some new techniques that we will focus on in the labs.

## Labs

- 2 hour session.
- You will code!
- **Part of the Course Material**.
    - You **will be assessed** on material from the labs.
    - I will attempt to record the labs, but cannot guarantee the quality of the recordings.
- Both lab worksheets and solutions will still be available to everyone.


## Office Hour

- Mondays at 13:00 (right before the lab) 
- In my office (Building 39, Room 2025).

## Assessment

- Four *take-home* mini courseworks. (5% each, total 20%)
    - Weeks 2, 4, 6 and 10.
    - You will have one week to complete each coursework.
    - Submission via `GitHub`.
    - Autograded.

## Assessment

- Two *in-person* supervised courseworks. (40% each, total 80%)
    - **A1** Week 8 - Tuesday 10th November, 11:00-13:00, 25/1009. Covers Chapters 1-6.
    - **A2** Week 12 - Tuesday, 8th December, 11:00-13:00, 25/1009. Covers the entire module.

## Assessment

- GenAI **allowed** in take-home, **blocked** in supervised coursework.
- Supervised coursework uses University computers.
- **You will not be able to complete the assessments if you do not know how to use:**
    - Git (take-home only)
    - Quarto Notebooks in `R`.
- These are covered in Chapters 2-3 *and in every lab*.

## Main Text

- "R for Data Science", https://r4ds.hadley.nz